### ISSUE TITLE
[Feature] Export nouveau : parrain, équipe et heure de passage

### ISSUE THREAD

**Issue by jdorel** [ungdev/integration-UTT#175]
Pour pouvoir informer les nouveaux au mieux lors de leur accueil, l'objectif sera de pouvoir exporter la liste des nouveaux avec : 
- leur nom et prénom
- leur branche
- le nom et prénom de leur parrain (+numéro de tél ?)
- le nom de leur équipe
- leur horaire de passage

Pour l'horaire de passage, il faudrait ajouter dans la table d'équipes la date et l'heure de passage, ainsi que dans la vue d'équpe leur horaire de passage.
Le bouton d'export devrait être dans la liste déroulante du menu export.

**Comment by jdorel** [comment]
Il reste le bouton d'export à faire :)

**Comment by larueli** [comment]
@jdorel j'ai édité l'export déjà présent Nouveaux -> Parrains, il y avait déjà tout sauf l'équipe et sa date de passage que j'ai rajouté
